// demo/angular/src/app/voice_widget.component.ts
import { Component, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';

import { PorcupineService } from '@picovoice/porcupine-angular';

import { BuiltInKeyword, PorcupineKeyword } from '@picovoice/porcupine-web';

// @ts-ignore
import porcupineModel from '../lib/porcupineModel';
// @ts-ignore
import porcupineKeywords from '../lib/porcupineKeywords';

if (porcupineKeywords.length === 0 && porcupineModel.publicPath.endsWith("porcupine_params.pv")) {
  for (const k in BuiltInKeyword) {
    // @ts-ignore
    porcupineKeywords.push({builtin: BuiltInKeyword[k]});
  }
}

@Component({
  selector: 'app-voice-widget',
  templateUrl: './voice_widget.component.html',
  styleUrls: ['./voice_widget.component.scss']
})
export class VoiceWidgetComponent implements OnDestroy {
  private keywordSubscription: Subscription;
  private isLoadedSubscription: Subscription;
  private isListeningSubscription: Subscription;
  private errorSubscription: Subscription;

  isLoaded = false;
  isListening = false;
  error: Error | string | null = null;

  detections: Array<string> = [];
  keywords: Array<string> = porcupineKeywords.map((k:any) => k.label ?? k.builtin);
  constructor(private porcupineService: PorcupineService) {
    // Subscribe to Porcupine Keyword detections
    // Store each detection, so we can display it in an HTML list
    this.keywordSubscription = porcupineService.keywordDetection$.subscribe(
      porcupineSubscription => {
        this.detections = [...this.detections, porcupineSubscription.label];
      });

    // Subscribe to isListening, isLoaded, and error
    this.isLoadedSubscription = porcupineService.isLoaded$.subscribe(
      isLoaded => {
        this.isLoaded = isLoaded;
      });
    this.isListeningSubscription = porcupineService.isListening$.subscribe(
      isListening => {
        this.isListening = isListening;
      });
    this.errorSubscription = porcupineService.error$.subscribe(
      error => {
        this.error = error;
      });
  }

  ngOnDestroy(): void {
    this.keywordSubscription.unsubscribe();
    this.isLoadedSubscription.unsubscribe();
    this.isListeningSubscription.unsubscribe();
    this.errorSubscription.unsubscribe();
    this.porcupineService.release();
  }

  public async stop(): Promise<void> {
    await this.porcupineService.stop();
  }

  public async start(): Promise<void> {
    await this.porcupineService.start();
  }

  public async initEngine(accessKey: string, selectedKeyword: string): Promise<void> {

    if (accessKey.length >= 0) {
      await this.porcupineService.release();
      try {
        await this.porcupineService.init(
          accessKey,
          porcupineKeywords[parseInt(selectedKeyword)],
          porcupineModel
        );
      }
      catch (error: any) {
        this.error = error;
      }
    }
  }

  public async release(): Promise<void> {
    await this.porcupineService.release();
  }
}

<div class="voice-widget" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <h1>VoiceWidget</h1>
  <h3>
    <label>
      AccessKey obtained from
      <a href="https://picovoice.ai/console/">Picovoice Console</a>:
      <input
        type="text"
        name="accessKey"
        [disabled]="isLoaded"
        #accessKey
      />
    </label>
    <button class="start-button" (click)="initEngine(accessKey.value, selectedKeyword.value)" [disabled]="isLoaded">
      Start Porcupine
    </button>
  </h3>
  <h3>Porcupine Loaded: {{ isLoaded }}</h3>
  <h3>Listening: {{ isListening }}</h3>
  <h3>Error: {{ error !== null }}</h3>
  <h3>
    <label>Keyword: </label>
    <select #selectedKeyword (change)="isListening ? initEngine(accessKey.value, selectedKeyword.value): undefined">
      <option *ngFor="let keyword of keywords; index as i;" value="{{i}}">{{ keyword }}</option>
    </select>
  </h3>
  <p class="error-message" *ngIf="error !== null">{{ error.toString() }}</p>

  <br />
  <button (click)="start()" [disabled]="error || !isLoaded || isListening">Start</button>
  <button (click)="stop()" [disabled]="error || !isLoaded || !isListening">Stop</button>
  <button (click)="release()" [disabled]="error || !isLoaded">Release</button>
  <h3>Keyword Detections:</h3>
  <ul>
    <li *ngFor="let keywordLabel of detections">"{{ keywordLabel }}"</li>
  </ul>
</div>

// demo/react/src/VoiceWidget.tsx
import {useEffect, useState} from "react";

import {BuiltInKeyword, PorcupineKeyword} from "@picovoice/porcupine-web";
import {usePorcupine} from "@picovoice/porcupine-react";

import porcupineModel from "./lib/porcupineModel";
import porcupineKeywords from "./lib/porcupineKeywords";

if (porcupineKeywords.length === 0 && porcupineModel.publicPath.endsWith("porcupine_params.pv")) {
  for (const k in BuiltInKeyword) {
    // @ts-ignore
    porcupineKeywords.push({builtin: k});
  }
}

export default function VoiceWidget() {
  const [keywordDetections, setKeywordDetections] = useState<string[]>([]);
  const [accessKey, setAccessKey] = useState("");
  const [keywords] = useState<Array<PorcupineKeyword>>(porcupineKeywords);

  const {
    keywordDetection,
    isLoaded,
    isListening,
    error,
    init,
    start,
    stop,
    release
  } = usePorcupine();

  const initEngine = async () => {
    await init(
      accessKey,
      keywords,
      porcupineModel
    );
  }

  useEffect(() => {
    if (keywordDetection !== null) {
      setKeywordDetections((oldVal) => [...oldVal, keywordDetection.label])
    }
  }, [keywordDetection])

  return (
    <div className="voice-widget">
      <h2>VoiceWidget</h2>
      <h3>
        <label>
          AccessKey obtained from{" "}
          <a href="https://console.picovoice.ai/">Picovoice Console</a>:
          <input
            type="text"
            name="accessKey"
            onChange={(value) => setAccessKey(value.target.value)}
          />
          <button
            className="init-button"
            onClick={() => initEngine()}
          >
            Init Porcupine
          </button>
        </label>
      </h3>
      <h3>Loaded: {JSON.stringify(isLoaded)}</h3>
      <h3>Listening: {JSON.stringify(isListening)}</h3>
      <h3>Error: {JSON.stringify(error !== null)}</h3>
      {error && (
        <p className="error-message">{JSON.stringify(error)}</p>
      )}
      <h3>Keywords:</h3>
      <h4>{porcupineKeywords.map(k => k.label ?? k.builtin).join(', ')}</h4>
      <br/>
      <button
        onClick={() => start()}
        disabled={error !== null || !isLoaded || isListening}
      >
        Start
      </button>
      <button
        onClick={() => stop()}
        disabled={error !== null ||!isLoaded || !isListening}
      >
        Stop
      </button>
      <button
        onClick={() => release()}
        disabled={error !== null || !isLoaded}
      >
        Release
      </button>
      <h3>Keyword Detections:</h3>
      {keywordDetections.length > 0 && (
        <ul>
          {keywordDetections.map((label: string, index: number) => (
            <li key={index}>{label}</li>
          ))}
        </ul>
      )}
    </div>
  );
}
