// demo/react/src/App.jsx
import "./App.css";
import { useState } from "react";

import VoiceWidget from "./VoiceWidget";

function App() {
  const [show, setShow] = useState(true);
  return (
    <div className="App">
      <h1>Porcupine Web + React Hook ("usePorcupine" from @picovoice/porcupine-web-react)</h1>
      <button onClick={() => setShow(!show)}>
        Toggle VoiceWidget {show ? "OFF" : "ON"}
      </button>
      <br />
      <br />
      {show && <VoiceWidget />}
    </div>
  );
}

export default App;

// demo/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'porcupine-angular-demo-porcupine';
  show = true;

  toggle(): void {
    this.show = !this.show;
  }
}

<style></style>
<h1>Porcupine Web + Angular</h1>
<button (click)="toggle()">Toggle VoiceWidget {{ show ? "OFF" : "ON" }}</button>
<br />
<br />

<app-voice-widget *ngIf="show"></app-voice-widget>
